# Generated by Django 2.0.4 on 2018-04-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='album',
            new_name='albums',
        ),
    ]
